name: RunesEnchant
version: 1.0
main: me.ayush_03.runesenchant.RunesEnchant
desscription: The famous RunesEnchant plugin is back boys!

commands:
  runes:
    usage: /<command> <args>
    description: Main command.