package me.ayushdev.runesenchant;

public enum StoneType {

    RESURRECTION, LUCK, ENCHANTMENT_ORB, PROTECTION_CHARM, INTANGIBILITY, LEERING, RETREAT, HEALING_ORB, TAIL_WIND;

    //    COAL       LAPIS     REDSTONE   EYE_OF_ENDER          SNOWBALL     NETHER_STAR
}
