rune-item: 'EMERALD:0'

success-rate: 92
destroy-rate: 12

slots-enabled: true
slots: 5
slot-display: '&6Slots: %slots%'

protection-enabled: true
protection-display: '&a&lPROTECTED'

rune-stacking: true

rune-drag-drop: true
enchanter: true