name: RunesEnchant
version: 1.0
main: me.ayushdev.runesenchant.RunesEnchant
desscription: The famous RunesEnchant plugin is back boys!
api-version: 1.16

commands:
  runes:
    usage: /<command> <args>
    description: Main command.

  ritem:
    usage: /<command> <args>
    description: Gives the special items.