name: RunesEnchant
version: 1.0.2
main: me.ayushdev.runesenchant.RunesEnchant
desscription: A premium custom enchantment plugin for Miencraft servers!
api-version: 1.16

commands:
  runes:
    usage: /<command> <args>
    description: Main command.

  ritem:
    usage: /<command> <args>
    description: Gives the special items.

  id:
    usage: /<command>
    description: Shows the item which you should use in the config.